Port: ":8881"
Username: "admin"
Password : "123"

Token-Key: "kfgJd"

MySqlUrl: root:123456@tcp(127.0.0.1:3306)/daily_work_log?charset=utf8mb4&parseTime=True&loc=Local
MySqlMaxIdle: 5
MySqlMaxOpen: 10

RedisCache:
  Host: ['127.0.0.1:6379']
  DB: 10
  Password:
  MaxIdle: 100
  MaxActive: 500
